trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  displayName: 'Maven otto-api-profile/pom.xml'
  inputs:
    testRunTitle: CItests
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx1024m'
    javaHomeOption: 'JDKVersion'
    codeCoverageToolOption: JaCoCo
    jdkVersionOption: 1.11
    jdkArchitectureOption: 'x64'
    checkStyleRunAnalysis: true
    pmdRunAnalysis: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    publishJUnitResults: true
    goals: 'package'

- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'